#!/usr/bin/env bash

static_conf="/home/mina/.dotfiles/static.yaml"

check_and_get_root_privs() {
    if ! has_root_privs; then
        echo "This script requires root privileges"
        get_root_privs
    fi
}

has_root_privs() {
    [[ "$EUID" == 0 ]]
}

get_root_privs() {
    sudo -v 2>/dev/null

    if ! has_root_privs; then
        echo "Failed to obtain root privileges"
        exit 2
    fi
}

check_netstat_exists() {
    if ! command -v "netstat" &>/dev/null; then
        echo "'netstat' command is not installed"
        echo "Installing net-tools..."

        sudo apt-get install -y net-tools >/dev/null
    fi
}

backup-dhcp-conf() {
    local dhcp_conf="/etc/netplan/00-installer-config.yaml"

    if [[ -f $dhcp_conf ]]; then
        sudo mv "$dhcp_conf" "/etc/netplan/00-installer-config.yaml.bak"
    fi
}

change_device_in_static_conf() {
    local eth_device
    eth_device="$(ip a | grep -B1 "link/ether" | cut -f2 -d " " | tr -d ":")"

    sed --quiet "s/enp0s3/$eth_device/" "$static_conf"
}

move_conf() {
    check_conf_exists

    cat "$static_conf" | sudo tee "/etc/netplan/static.yaml" >/dev/null
}
check_conf_exists() {
    if [[ ! -e $static_conf ]]; then
        echo "Static config file doesn't exist, please clone the dotfiles repo"

        exit 3
    fi
}

apply_conf() {
    sudo netplan apply >/dev/null
}

main() {
    echo -e "Please do not exit the script before it finishes\n"

    check_and_get_root_privs
    check_netstat_exists
    backup-dhcp-conf

    change_device_in_static_conf
    move_conf
    apply_conf

    echo "Static IP configuration complete."
    echo "Don't forget to change ip in your client ssh config."
    sleep 2 #? to wait for network to restart
    exit 0
}

main
